### ISSUE TITLE
Autocomplete suggestions

### ISSUE THREAD

**Issue by casparvitch** [MasFlam/jlabbrev#2]
Hi thanks for the very nice plugin.

How do I 'complete' on the autocomplete suggestions?

E.g. if I type `\diag` and hit tab, suggestions come up for `diagup  diagdown`, with `diagup` selected, and I can hit tab to cycle through them.
However I can't work out how to 'select' which of these suggestions I want.

Much appreciated

**Comment by masflam** [comment]
<kbd>Enter</kbd> should insert the current suggestion. If that doesn't work for some reason, worst case you can type `\diagu` and then press <kbd>Tab</kbd>.

**Comment by casparvitch** [comment]
Thanks for the response! 

Sorry I forgot a key detail, when I hit `Enter` on the `\diagup` suggestion (from `\diag`), it autocompletes to `\diagup` (without converting to `╱`), and adds a newline. So to go from `\diag` to `╱` requires four key presses (`Tab`, `Enter`, `Backspace`, `Tab`).

By contrast when I `Tab` on `\diagu`, it goes autocompletes to `\diagup`, moving the cursor to the end of the term, so I can then `Tab` to convert to `╱`.

Anyway not a very important annoyance, and perhaps something to do with my terminal emulator (Konsole).
Thanks for the plugin and your help!

**Comment by masflam** [comment]
Gotta love those terminal input quirks :/
